properties([disableConcurrentBuilds()])
pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    environment {
        IMAGE = ""
        VERSION = ""
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        skipDefaultCheckout(true)
        skipStagesAfterUnstable()
        timestamps()
    }
    stages {
        stage('Prepare') {
            steps {
                echo "=============================== STARTING PREPARE ====================================="
                checkout scm
                script {
                    IMAGE = readMavenPom().getArtifactId().toLowerCase()
                    VERSION = readMavenPom().getVersion().toLowerCase()
                }
                echo IMAGE
                echo VERSION
                echo "=============================== END PREPARE ====================================="
            }
        }
        stage('Build') {
            steps {
                echo "=============================== STARTING BUILD ====================================="
                withMaven(maven: 'maven-latest') {
                    bat " mvn clean install"
                }
                echo "=============================== BUILD SUCCESSFUL ==================================="
            }
        }
        stage('Execute') {
            steps {
                echo "=============================== STARTING EXECUTE ====================================="
                script {
                    bat """
                    cd target
                    java -jar seq.jar --sequence="(4*x*x*x)+((3/4)*x*x)+(2*x)-11" --number=44
                    """
                }
                echo "=============================== FINISH ==================================="
            }
        }
    }
}